<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\simulado.data\simulado.data.csproj" />
    <ProjectReference Include="..\simulado.shared\simulado.shared.csproj" />
  </ItemGroup>

</Project>
