// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using simulado.data.Context;

#nullable disable

namespace simulado.data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251106124043_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("simulado.shared.Entidades.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Nome")
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categorias", (string)null);
                });

            modelBuilder.Entity("simulado.shared.Entidades.Concurso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<Guid>("NivelEscolaridadeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("NivelEscolaridadeId");

                    b.ToTable("Concursos", (string)null);
                });

            modelBuilder.Entity("simulado.shared.Entidades.Desempenho", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConcursoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataDesempenho")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("PercentualAcerto")
                        .HasColumnType("double precision");

                    b.Property<int>("QuestoesCorretas")
                        .HasColumnType("integer");

                    b.Property<int>("QuestoesErradas")
                        .HasColumnType("integer");

                    b.Property<Guid>("SimuladoId")
                        .HasColumnType("uuid");

                    b.Property<int>("TotalQuestoes")
                        .HasColumnType("integer");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ConcursoId");

                    b.HasIndex("SimuladoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Desempenhos", (string)null);
                });

            modelBuilder.Entity("simulado.shared.Entidades.Disciplina", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Disciplinas", (string)null);
                });

            modelBuilder.Entity("simulado.shared.Entidades.NivelEscolaridade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("NivelEscolaridades", (string)null);
                });

            modelBuilder.Entity("simulado.shared.Entidades.Questao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DisciplinaId")
                        .HasColumnType("uuid");

                    b.Property<string>("RespostaCerta")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RespostaErradaDois")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RespostaErradaQuatro")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RespostaErradaTres")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RespostaErradaUm")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<Guid>("SimuladoId")
                        .HasColumnType("uuid");

                    b.Property<string>("TextoPergunta")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("DisciplinaId");

                    b.HasIndex("SimuladoId");

                    b.ToTable("Questoes", (string)null);
                });

            modelBuilder.Entity("simulado.shared.Entidades.RespostaUsuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataResposta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EstaCorreta")
                        .HasColumnType("boolean");

                    b.Property<Guid>("QuestaoId")
                        .HasColumnType("uuid");

                    b.Property<string>("RespostaDada")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<Guid>("SessaoSimuladoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("QuestaoId");

                    b.HasIndex("SessaoSimuladoId");

                    b.ToTable("RespostasUsuario", (string)null);
                });

            modelBuilder.Entity("simulado.shared.Entidades.SessaoSimulado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Pontuacao")
                        .HasColumnType("double precision");

                    b.Property<Guid>("SimuladoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SimuladoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("SessoesSimulado", (string)null);
                });

            modelBuilder.Entity("simulado.shared.Entidades.Simulado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConcursoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("ConcursoId");

                    b.ToTable("Simulados", (string)null);
                });

            modelBuilder.Entity("simulado.shared.Entidades.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("NivelEscolaridadeId")
                        .HasColumnType("uuid");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NivelEscolaridadeId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("simulado.shared.Entidades.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("simulado.shared.Entidades.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("simulado.shared.Entidades.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("simulado.shared.Entidades.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("simulado.shared.Entidades.Concurso", b =>
                {
                    b.HasOne("simulado.shared.Entidades.Categoria", "Categoria")
                        .WithMany("Concursos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("simulado.shared.Entidades.NivelEscolaridade", "NivelEscolaridade")
                        .WithMany("Concursos")
                        .HasForeignKey("NivelEscolaridadeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("NivelEscolaridade");
                });

            modelBuilder.Entity("simulado.shared.Entidades.Desempenho", b =>
                {
                    b.HasOne("simulado.shared.Entidades.Concurso", "Concurso")
                        .WithMany("Desempenhos")
                        .HasForeignKey("ConcursoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("simulado.shared.Entidades.Simulado", "Simulado")
                        .WithMany("Desempenhos")
                        .HasForeignKey("SimuladoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("simulado.shared.Entidades.Usuario", "Usuario")
                        .WithMany("Desempenhos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Concurso");

                    b.Navigation("Simulado");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("simulado.shared.Entidades.Questao", b =>
                {
                    b.HasOne("simulado.shared.Entidades.Disciplina", "Disciplina")
                        .WithMany("Questoes")
                        .HasForeignKey("DisciplinaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("simulado.shared.Entidades.Simulado", "Simulado")
                        .WithMany("Questoes")
                        .HasForeignKey("SimuladoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Disciplina");

                    b.Navigation("Simulado");
                });

            modelBuilder.Entity("simulado.shared.Entidades.RespostaUsuario", b =>
                {
                    b.HasOne("simulado.shared.Entidades.Questao", "Questao")
                        .WithMany("RespostasUsuario")
                        .HasForeignKey("QuestaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("simulado.shared.Entidades.SessaoSimulado", "SessaoSimulado")
                        .WithMany("RespostasUsuario")
                        .HasForeignKey("SessaoSimuladoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Questao");

                    b.Navigation("SessaoSimulado");
                });

            modelBuilder.Entity("simulado.shared.Entidades.SessaoSimulado", b =>
                {
                    b.HasOne("simulado.shared.Entidades.Simulado", "Simulado")
                        .WithMany("SessoesSimulado")
                        .HasForeignKey("SimuladoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("simulado.shared.Entidades.Usuario", "Usuario")
                        .WithMany("SessoesSimulado")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Simulado");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("simulado.shared.Entidades.Simulado", b =>
                {
                    b.HasOne("simulado.shared.Entidades.Concurso", "Concurso")
                        .WithMany("Simulados")
                        .HasForeignKey("ConcursoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Concurso");
                });

            modelBuilder.Entity("simulado.shared.Entidades.Usuario", b =>
                {
                    b.HasOne("simulado.shared.Entidades.NivelEscolaridade", "NivelEscolaridade")
                        .WithMany("Usuarios")
                        .HasForeignKey("NivelEscolaridadeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NivelEscolaridade");
                });

            modelBuilder.Entity("simulado.shared.Entidades.Categoria", b =>
                {
                    b.Navigation("Concursos");
                });

            modelBuilder.Entity("simulado.shared.Entidades.Concurso", b =>
                {
                    b.Navigation("Desempenhos");

                    b.Navigation("Simulados");
                });

            modelBuilder.Entity("simulado.shared.Entidades.Disciplina", b =>
                {
                    b.Navigation("Questoes");
                });

            modelBuilder.Entity("simulado.shared.Entidades.NivelEscolaridade", b =>
                {
                    b.Navigation("Concursos");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("simulado.shared.Entidades.Questao", b =>
                {
                    b.Navigation("RespostasUsuario");
                });

            modelBuilder.Entity("simulado.shared.Entidades.SessaoSimulado", b =>
                {
                    b.Navigation("RespostasUsuario");
                });

            modelBuilder.Entity("simulado.shared.Entidades.Simulado", b =>
                {
                    b.Navigation("Desempenhos");

                    b.Navigation("Questoes");

                    b.Navigation("SessoesSimulado");
                });

            modelBuilder.Entity("simulado.shared.Entidades.Usuario", b =>
                {
                    b.Navigation("Desempenhos");

                    b.Navigation("SessoesSimulado");
                });
#pragma warning restore 612, 618
        }
    }
}
